jobframework-primary:
  image: "odaniait/job-framework:latest"
  ports:
    - "${PORT}:8000"
  labels:
    io.rancher.sidekicks: jobframework-datavolume
    io.rancher.container.hostname_override: container_name
  volumes_from:
    - jobframework-datavolume
jobframework-datavolume:
  image: "busybox"
  volumes:
    - /srv
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["chown", "-R", "1000:1000", "/srv"]
